FROM alpine:latest  

RUN apk update && \
    apk add --no-cache ffmpeg curl tar

WORKDIR /app/

RUN mkdir /downloads

RUN wget https://github.com/5rahim/seanime/releases/download/v2.1.1/seanime-2.1.1_Linux_x86_64.tar.gz && tar -xzf seanime-2.1.1_Linux_x86_64.tar.gz

ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

CMD ["./seanime"]
